config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root to: "pages#home"

  devise_for :users

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :lists, only: [:index, :show, :new, :create, :destroy]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: [:create]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "about" => "pages#about", as: :about
  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:index, :show]
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
<<<<<<< HEAD
    has_many :messages
    
end

=======
    has_many :messages, dependent: :destroy
end
>>>>>>> e37754df70e9b768f1c8ce16fa7e90a53f6cb274

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController


  def index
      @chatrooms = Chatroom.all

  end

  def show
      @chatroom = Chatroom.find(params[:id])
      @message = Message.new


  end
end

app/views/chatrooms/index.html.erb
<div id="chat" class="container">
  <% @chatrooms.each do |chatroom| %>
    <% artisan = User.find(chatroom.artisan_id) %>
    <% last_message = chatroom.messages.last %>
    <%= link_to chatroom_path(chatroom) do %>
      <div class="notification">
        <%= cl_image_tag artisan.photo.key, class: "avatar-large" %>
        <div class="notification-content">
          <p class="text-dark"><%= artisan.first_name  %></p>
          <% if last_message %>
            <p><%= last_message.content %></p>
          <% else %>
            <p>No messages yet.</p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/chatrooms/show.html.erb
<div class="container chatroom"
data-controller="chatroom-subscription"
data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">
<% artisan = User.find(@chatroom.artisan_id) %>
  <h1><%= artisan.first_name  %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message  %>
    <% end %>
  </div>
    <%= simple_form_for [@chatroom, @message],
    html: {class: "d-flex", data: { action: "turbo:submit-end->chatroom-subscription#resetForm", class: "d-flex"}} do |f|
    %>
    <%= f.input :content,
        label: false,
        placeholder: "Message #{@chatroom.name}",
        wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
    <% end %>
</div>