config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root to: "pages#home"

  devise_for :users

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :lists, only: [:index, :show, :new, :create, :destroy]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: [:create]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "about" => "pages#about", as: :about
  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:index, :show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-dark">
<footer>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-3 item">
            <h3>Services</h3>
            <ul>
                <li><a href="#">Hand made items</a></li>
                <li><a href="#">linking intrested people with</a></li>
                <li><a href="#">Hosting</a></li>
            </ul>
        </div>
        <div class="col-sm-6 col-md-3 item">
            <h3>About</h3>
            <ul>
                <li><a href="#">Company</a></li>
                <li><a href="#">Team</a></li>
                <li><a href="#">Careers</a></li>
            </ul>
        </div>
        <div class="col-md-6 item text">
            <a href="https://www.lewagon.com/"><img src="https://d26jy9fbi4q9wx.cloudfront.net/assets/logo-ae2beeecce25d711f577b08deb9adfc6c02b673ed106b8d6c3da0f1721d9da33.svg" alt="Le wagon"></a>
            <a href="https://jobintech.academy/"><img src="https://jobintech.academy/wp-content/uploads/2023/05/cropped-Untitled-design-1-1.png" alt="Jobintech"></a>
            <h3>BAZ'ART</h3>
            <p>Every purchase supports local craftsmen and contributes to the vibrancy of our creative community.
            Join us in celebrating craftsmanship, creativity, and community at Baz'art!</p>
        </div>
        <div class="col item social">
            <a class="bg-white" href="#"><i class="fa-brands fa-facebook"></i></a>
            <a class="bg-white" href="#"><i class="fa-solid fa-x"></i></a>
            <a class="bg-white" href="#"><i class="fa-brands fa-instagram"></i></a>
        </div>
    </div>
    <p class="copyright">BAZ'ART © 2024</p>
</div>
</footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> 
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
         <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Category", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Customize", "#", class: "nav-link" %>
        </li>
      </ul>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="" aria-label="Search">
        
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="position:sticky; background:white;">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dt9msp03i/image/upload/v1706870173/logo_black_ktju2o.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
         <li class="nav-item active">
          <%= link_to "Home", root_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Category", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Customize", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", chatrooms_path, class: "nav-link" %>
        </li>
      </ul>

      <form class="d-flex" action="/products" method="get">
        <input class="form-control me-2" name="search" type="search" placeholder="" aria-label="Search">
        <button class="btn btn-outline-success border-0" type="submit"><i class="fas fa-search"></i></button>
      </form>
        <% if user_signed_in? %>
          <div class="nav-item dropdown ps-3">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= cl_image_tag current_user.photo.key, class:"avatar" %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>