config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root to: "pages#home"

  devise_for :users

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :lists, only: [:index, :show, :new, :create, :destroy]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: [:create]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "about" => "pages#about", as: :about
  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:index, :show]
end

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Baz'art - About Us</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f8f8;
      color: #333;
      margin: 0;
      padding: 0;
    }

    h1, h2 {
      text-align: center;
      margin: 20px 0;
      font-weight: bold;
      text-shadow: 2px 2px 10px #F8F8FF;
    }

    h2 {
      color: #656463;
      text-shadow: 2px 2px 10px #F8F8FF
    }

    .about-container {
      text-align: center;
      color: #888;
      padding: 20px;
      background-image: url('https://img.freepik.com/photos-gratuite/tailleur-creatif-travaillant-atelier_23-2148970727.jpg?w=740&t=st=1707470927~exp=1707471527~hmac=e9a0bdbfadb4eb6416437f143a14c4b93a8d93128ab01adbac35b8cbf44d8c53');
      background-size: cover;
      background-position: center;
      margin: 20px auto;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .about-container .description {
      font-size: 18px;
      color: #333;
      line-height: 1.5em;
      margin: 0 auto;
      padding: 1em;
      background-color: rgba(255, 255, 255, 0.6); /* Ajoute un fond blanc semi-transparent */
      border-radius: 10px;
    }

    .team-container {
      text-align: center;
      padding: 30px;
      background-color: rgba(255, 255, 255, 0.6);
      margin: 30px auto;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .team-title {
      font-size: 24px;
      font-weight: bold;
      color: #333;
    }

    .team-member {
      margin-top: 20px;
    }

    .team-image img {
      width: 100px;
      height: 100px;
      border-radius: 50%;
    }

    .content h4 {
      margin: 10px 0 5px;
      font-size: 18px;
      font-weight: bold;
      color: #333;
    }

    .content span {
      font-size: 14px;
      color: #888;
    }

    .social {
      list-style: none;
      padding: 0;
      margin: 10px 0 0;
    }

    .social li {
      display: inline-block;
      margin-right: 5px;
    }

    .social a {
      display: block;
      width: 30px;
      height: 30px;
      border-radius: 50%;
      background-color: #007bff;
      text-align: center;
      line-height: 30px;
      color: #fff;
    }

   .partners-section {
  text-align: center;
  margin: 20px auto;
}

.partners-section h2 {
  font-weight: bold;
  color: #333;
}

.partner-container {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
}

.partner {
  margin: 20px;
  padding: 20px;
  background-color: rgba(255, 255, 255, 0.8);
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.partner img {
  max-width: 100px;
  height: auto;
}

.partner-info {
  margin-top: 20px;
}

.partner-info h3 {
  font-size: 1.2rem;
  color: #555;
  margin-bottom: 10px;
}

.partner-info p {
  font-size: 0.9rem;
  color: #777;
}

  </style>

</head>
<body>
  <div class="about-container">
    <h1 style="color: black; ">About us</h1>
    <div class="description" style="width:70%;" >_____________________________________________<br><br>
      Baz'art is a platform that showcases the beauty of authentic handmade products from Morocco. It was founded with the goal of providing a global stage for artisans and their creations, emphasizing the cultural narrative behind each handmade piece. The platform celebrates the fusion of tradition and innovation and offers a diverse range of products including metalwork, pottery, leather, and furniture.<br><br>
      Every product on Baz'art has its own unique story, reflecting the company's commitment to quality, authenticity, and timeless beauty. They believe that each handmade creation carries the essence of Moroccan craftsmanship and aims to make every purchase an opportunity to connect with the heart and soul of this rich tradition. By bringing these meaningful objects into your home, you can create a living canvas that embodies the spirit of Moroccan craftsmanship.<br><br>
    </div>
    <h2 class="welcome" style="color:black;">Welcome to Baz'art, where the beauty of handmade products is celebrated and cherished.</h2>
  </div>

   <!-- Team Section -->
   <div class="container">
  <div class="team-container">
    <div class="section-title">
      <h2>Our Team</h2>
<p>Baz'art brings together a diverse and talented team dedicated to showcasing the beauty of handmade products from Morocco. Our passionate artisans and creators work collaboratively, blending tradition with innovation to offer a unique collection of metalwork, pottery, leather, and furniture. Each team member is committed to the values of quality, authenticity, and timeless beauty.</p>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6 col-12">
        <!-- Start Single Team -->
        <div class="team-member">
          <div class="team-image">
            <img src="https://ca.slack-edge.com/T02NE0241-U06A735D2P2-02a878a3af19-192" alt="#">
          </div>
          <div class="content">
            <h4>Ali Mercade <span>Founder</span></h4>
            <ul class="social">
              <li><a href="javascript:void(0)"><i class="fa-brands fa-linkedin"></i></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-brands fa-github"></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-brands fa-twitter"></i></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-solid fa-phone"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End Single Team -->
      </div>
      <!-- Add more team members as needed -->

      <div class="col-lg-3 col-md-6 col-12">
        <!-- Start Single Team -->
        <div class="team-member">
          <div class="team-image">
            <img src="https://ca.slack-edge.com/T02NE0241-U0693N5R44X-7f2adc5f7f11-192" alt="#">
          </div>
          <div class="content">
            <h4>Ihsane Ennaji <span>Founder</span></h4>
            <ul class="social">
              <li><a href="javascript:void(0)"><i class="fa-brands fa-linkedin"></i></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-brands fa-github"></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-brands fa-twitter"></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-solid fa-phone"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End Single Team -->
      </div>
      <!-- Add more team members as needed -->

      <div class="col-lg-3 col-md-6 col-12">
        <!-- Start Single Team -->
        <div class="team-member">
          <div class="team-image">
            <img src="https://ca.slack-edge.com/T02NE0241-U069F9E2WTX-f032a4454756-192" alt="#">
          </div>
          <div class="content">
            <h4>Zakaria Boudhaim <span>Founder</span></h4>
            <ul class="social">
              <li><a href="javascript:void(0)"><i class="fa-brands fa-linkedin"></i></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-brands fa-github"></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-brands fa-twitter"></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-solid fa-phone"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End Single Team -->
      </div>
      <!-- Add more team members as needed -->

      <div class="col-lg-3 col-md-6 col-12">
        <!-- Start Single Team -->
        <div class="team-member">
          <div class="team-image">
            <img src="https://ca.slack-edge.com/T02NE0241-U069J73S9LJ-11426ae35f53-192" alt="#">
          </div>
          <div class="content">
            <h4>Zaid Dakir <span>Founder</span></h4>
            <ul class="social">
               <li><a href="javascript:void(0)"><i class="fa-brands fa-linkedin"></i></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-brands fa-github"></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-brands fa-twitter"></i></i></a></li>
              <li><a href="javascript:void(0)"><i class="fa-solid fa-phone"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End Single Team -->
      </div>
      <!-- Add more team members as needed -->
    </div>
  </div>
  <!-- End Team Section -->

<div class="partners-section">
  <h2><strong>Our partners</strong></h2>
  <div class="partner">
<img height="43" width="163" alt="Le Wagon" class="img-fluid" src="https://www.lewagon.com/assets/v4/logo-lewagon-9c19fb39a748cd3b1f49059ce0dc6c0dfc4cc2447d5a9a3e01bd2d5a214faf3c.svg">    <p>Le Wagon is a coding training school that teaches you how to code and change careers or launch your own start-up.</p>
  </div>
  <div class="partner">
    <img src="https://jobintech.academy/wp-content/uploads/2023/05/cropped-Untitled-design-1-1.png" alt="Logo JobInTech">
    <p>JobInTech is an initiative aimed at creating a large pool of qualified IT professionals ready for employment.</p>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<div>
<div class="banner">

</div>

<div class="container justify-content-center">
  <h1 class="solgan">“Your Artisan Haven for <br>Inspired Living”</h1>
  <p class="text">For two weeks, Baz'Art t has been creating authentic, contemporary and timeless furniture from solid wood and natural materials. With outstanding craftsmanship at the core of the brand, our Morrocan-based company believes in creating quality wooden furniture that lasts for generations and withstands trends. Discover our iconic solid wood dining tables, dining chairs in solid wood, sideboards, textile accessories collection and much more.</p>

  <div style="margin-top: 0.5rem; margin-bottom: 4rem; text-align: center; padding-right: 4vw; padding-left: 4vw;">
    <a class="homepage-discover-more-btn" href="/about">
      <button style="border: 1px; border-radius: 8px; border-style: solid; background-color: black; border-color: black; padding: 6px 20px; text-decoration: none; display: inline-block; font-weight: 300; font-size: 14px; margin: 4px 2px; cursor: pointer; color: white;"
              onmouseover="this.style.border='1px solid #000000'; this.style.backgroundColor='#ffffff'; this.style.color='#000000';"
              onmouseout="this.style.border='1px solid black'; this.style.backgroundColor='black'; this.style.color='white';">
        Discover more
      </button>
    </a>
  </div>
</div>
<div id="collection-cards" class="d-flex justify-content-center ">
    <%= link_to products_path(collection: "chairs") do %>
          <div class="card m-4">
            <div class="image-box">
              <img src="https://api.cy0e40h2m3-ethnicraf1-p1-public.model-t.cc.commerce.ondemand.com/medias/Bok-chair-solid-oak-Ethnicraft.jpg?context=bWFzdGVyfGltYWdlc3wyOTk2MTN8aW1hZ2UvanBlZ3xoMjIvaDM0Lzg5NDQxMjEzODA4OTQvQm9rX2NoYWlyX3NvbGlkX29ha19FdGhuaWNyYWZ0LmpwZ3w2MDIxMWRlNWIyMDYxZTljZWJmYjkwNzY1ZTUxOTI0MDYyMGY0YzBlYWI1Y2QxMzYxN2I0MGIzNGYzMTAxZTgw" alt="">
              <div class="content text-center py-3 h4 card-title" style="color: white; font-weight: bold;">
                <%= "chairs" %>
              </div>
            </div>
          </div>
    <% end %>
    <%= link_to products_path(collection: "pots") do %>
          <div class="card m-4">
            <div class="image-box">
              <img src="https://images.pexels.com/photos/8063809/pexels-photo-8063809.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="">
              <div class="content text-center py-3 h4 card-title" style="color: white; font-weight: bold;">
                <%= "pots" %>
              </div>
            </div>
          </div>
    <% end %>
    <%= link_to products_path(collection: "chandeliers") do %>
          <div class="card m-4">
            <div class="image-box">
              <img src="https://images.pexels.com/photos/2363826/pexels-photo-2363826.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="">
              <div class="content text-center py-3 h4 card-title" style="color: white; font-weight: bold;">
                <%= "chandelier" %>
              </div>
            </div>
          </div>
    <% end %>
</div>

<div class="container mt-5">
  <div class="text-center">
    <div>
      <img src="https://res.cloudinary.com/dt9msp03i/image/upload/v1706879875/cat-han-VgyN_CWXQVM-unsplash_qduiwi.jpg" alt="Image">
    </div>
    <div class="box info">
      <p>Find a store near you</p>
      <a href="<%= users_path %>"><input type="button" class="btn-1" value="Store locator"></a>
    </div>
  </div>
</div>

<div class="video-container">
  <video autoplay loop muted playsinline>
    <source src="https://res.cloudinary.com/dt9msp03i/video/upload/v1706887959/pexels-polina-kovaleva-5644278_1080p_sinw0x.mp4" type="video/mp4">
    Your browser does not support the video tag.
  </video>
</div>

<div class="container mt-5">
    <div class="eth-main-banner__square bg-wild_sand eth-main-banner__square--center">
        <h2 class="eth-main-banner__title text-on-image text-black"> Let's work together! </h2>
        <div class="text-black"> Designing a new space? Discover our offer for contract & trade professionals </div>
        <div class="container mt-3">
            <a class="eth-main-banner__link btn btn-oak" href="/about" target="_blank"> Contact our team </a>
        </div>
    </div>
</div>