config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root to: "pages#home"

  devise_for :users

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :lists, only: [:index, :show, :new, :create, :destroy]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: [:create]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "about" => "pages#about", as: :about
  # Defines the root path route ("/")
  # root "posts#index"

  resources :users, only: [:index, :show]
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :collection, presence: true
  validates :material, presence: true
  validates :color, presence: true

  COLLECTION = %w(chairs tables lamps shelves desks pots sofas chandeliers vases jewelry)
  MATERIAL = %w(Gold Silver Bronze glass wood plastic pottery clay marble plaster aluminum)
  COLOR = %w(Red Blue Green Yellow Black White Purple Brown)

  has_many :reviews
  belongs_to :craftman, class_name: "User", foreign_key: "craftman_id"
  has_many :lists
  has_many :clients, through: :lists, class_name: "User", foreign_key: "client_id"

  has_one_attached :photo
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @products = Product.all

    if params[:search].present?
      @products = @products.where("title ILIKE ?", "%#{params[:search]}%")
    end

    if params[:collection].present?
      @products = @products.where(collection: params[:collection])
    elsif params[:material].present?
      @products = @products.where(material: params[:material])
    elsif params[:color].present?
      @products = @products.where(color: params[:color])
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.craftman = current_user
    if @product.save!
      redirect_to product_path(@product.id)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    if @product.update(product_params)
      flash[:success] = "Product Updated Successfully"
      redirect_to "/products/#{product.id}"
    else
      flash[:warning] = "Product Not Updated"
      redirect_to "/products/#{product.id}/edit"
    end
  end

  def update

  end

  def destroy
    @product = Product.destroy
    redirect_to "/products"
  end



  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :price, :description, :collection, :material, :color, :photo)
  end
end

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.select :collection,  collection: Product::COLLECTION %>
<%= f.select :material,  collection: Product::MATERIAL %>
<%= f.select :color,  collection: Product::COLOR %>
<%= f.input :photo, as: :file %>
<%= f.submit %>

<% end %>

app/views/products/index.html.erb
<div class="container">
<div class="d-flex justify-content-center  ">

<%= form_tag(products_path, method: "get", class:"d-flex align-items-center") do %>

  <%= select_tag :collection, options_for_select([["Collection", ""]].concat(Product.pluck(:collection).uniq.map { |collection| [collection, collection] }), params[:collection]), class: "select" %>

<%= select_tag :material, options_for_select([["Material", ""]].concat(Product.pluck(:material).uniq.map { |material| [material, material] }), params[:material]), class: "select" %>

<%= select_tag :color, options_for_select([["Color", ""]].concat(Product.pluck(:color).uniq.map { |color| [color, color] }), params[:color]), class: "select" %>
  <%= submit_tag "Filter" , class:"button-6 m-2" %>
  <% if current_user %>
<%= link_to "Add Product", new_product_path(@product), class:"button-6 mr-5" %>
<% end %>
<% end %>
</div>

<div class="d-flex justify-content-center mt-3">
<div id="cards">
<% @products.each do |product| %>
<%= link_to product do %>
<div class="card-trip text-dark" style="height:310px;">
 <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="card-trip-infos">
    <div>
      <h2><%= product.title %></h2>
      <p><%= product.description %></p>
    </div>

    <h2 class="card-trip-pricing "><div class="d-flex"><%= product.price %> <h2>    Dh</h2> </div></h2>
    <%= cl_image_tag product.craftman.photo.key, class: "card-trip-user avatar-bordered" %>
    </div>

  </div>
  <% end %>
  <% end %>
</div>
</div>
</div>

app/views/products/new.html.erb
<div class="container w-50 shadow">

<h1 class="text-center">New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path, class:"btn btn-primary my-5" %>
</div>

app/views/products/show.html.erb
<div class="container">
    <div class="category">
        <h1><%= @product.collection.capitalize  %></h1>
    </div>
    <div class="product_info">
        <div class="image">
            <%= cl_image_tag @product.photo.key, height: 400, width: 500, crop: :fill %>
        </div>
        <div class="description">
            <div class="scroll">
                <div class="category-container">
                    <div class="dropdown">
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Collection
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Chairs</a>
                            <a class="dropdown-item" href="#">Desks</a>
                            <a class="dropdown-item" href="#">Carpets</a>
                        </div>
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Material
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Pottery</a>
                            <a class="dropdown-item" href="#">Wood</a>
                            <a class="dropdown-item" href="#">Metal</a>
                        </div>
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Color
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Green</a>
                            <a class="dropdown-item" href="#">Gold</a>
                            <a class="dropdown-item" href="#">Green</a>
                        </div>
                    </div>
                </div>
            </div>
            <h2><%= @product.title %></h2>
            <p><%= @product.description %></p>
            <p><%= number_to_currency @product.price %></p>

            <%= link_to "Find artisan", user_path(@product.craftman), class:"btn btn-outline-dark" %>
        </div>
    </div>
</div>